import express from 'express';
import { getGoals, addGoal, updateGoal, deleteGoal } from '../controllers/goalController.js';
import auth from '../middleware/auth.js';
const router = express.Router();
router.use(auth);
router.get('/', getGoals);
router.post('/', addGoal);
router.put('/:id', updateGoal);
router.delete('/:id', deleteGoal);
export default router;
