# Generated by Django 6.0.1 on 2026-01-06 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('file', models.FileField(upload_to='manuscripts/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('DECISION_READY', 'Decision Ready'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('REVISION_REQ', 'Revision Required')], default='SUBMITTED', max_length=20)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscripts', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, limit_choices_to={'role': 'EDITOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_manuscripts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
