# Generated by Django 6.0.1 on 2026-01-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
