# Generated by Django 6.0.1 on 2026-01-08 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_manuscript_last_updated_manuscript_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manuscript',
            options={'ordering': ['-submission_date']},
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='last_updated',
        ),
    ]
